language: php

php:
  - 5.3
  - 5.4

env:
  - SYMFONY_VERSION=2.1.*
  - SYMFONY_VERSION=2.2.*
  - SYMFONY_VERSION=2.3.*

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar require symfony/framework-bundle:${SYMFONY_VERSION} --no-update --dev
  - php composer.phar install --verbose --dev --prefer-source --no-interaction -o

script: phpunit

notifications:
    email:
        - abhoryo@free.fr
        - zend@i.ua
