language: php

php:
  - 5.3
  - 5.4

env:
  - SYMFONY_VERSION=origin/2.1
  - SYMFONY_VERSION=origin/2.2
  - SYMFONY_VERSION=origin/2.3

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: phpunit

notifications:
    email:
        - abhoryo@free.fr
        - zend@i.ua
